--名称
appname="一键生成APP"
--版本号
appver="1.8 beta"
--版本
appcode="1"
--SDK
appsdk="21"
--包名
packagename="com.AweQY.app"
--调试模式
debugmode=false
--应用权限
user_permission={
  "BIND_ACCESSIBILITY_SERVICE",
  "CHANGE_NETWORK_STATE",
  "CHANGE_WIFI_STATE",
  "DOWNLOAD_WITHOUT_NOTIFICATION",
  "FOREGROUND_SERVICE",
  "GET_PACKAGE_SIZE",
  "GET_TASKS",
  "INSTALL_SHORTCUT",
  "INTERNET",
  "KILL_BACKGROUND_PROCESSES",
  "READ_EXTERNAL_STORAGE",
  "READ_PHONE_STATE",
  "REQUEST_INSTALL_PACKAGES",
  "SET_WALLPAPER",
  "SYSTEM_ALERT_WINDOW",
  "VIBRATE",
  "WAKE_LOCK",
  "WRITE_EXTERNAL_STORAGE",
  "WRITE_SETTINGS",
}
--跳过编译
skip_compilation={

}